name: build
permissions:
  contents: read
on:
  schedule:
    - cron:  '0 5 * * 5'
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.mold }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - SimpleAlloy
          - ArchLinux

    steps:
    - name: Increase free space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build goldboot image
      uses: fossable/goldboot-action@main
      with:
        context: ${{ matrix.name }}
        output: ${{ matrix.name }}.gb
        # record: true
        # debug: true

    # TODO push to registry

    - name: Store debug output
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Debug output
        path: './screenshots'
